In [1]:
import pandas as pd
import numpy as np
import os
import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, StringType

In [2]:
spark = SparkSession.builder \
    .appName('airlines_delay')\
    .config('spark.jars', '../../jars/snowflake-jdbc-3.13.6.jar, ../../jars/spark-snowflake_2.12-2.9.0-spark_3.1.jar') \
    .getOrCreate()

22/10/25 13:42:34 WARN Utils: Your hostname, CNWFGPGV77 resolves to a loopback address: 127.0.0.1; using 192.168.0.106 instead (on interface en0)
22/10/25 13:42:34 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
22/10/25 13:42:34 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).

In [3]:
cols = ['Year',
    'Quarter',
    'Month',
    'DayofMonth',
    'DayOfWeek',
    'FlightDate',
    'Reporting_Airline',
    'DOT_ID_Reporting_Airline',
    'IATA_CODE_Reporting_Airline',
    'Tail_Number',
    'Flight_Number_Reporting_Airline',
    'OriginAirportID',
    'Origin',
    'OriginCityName',
    'OriginState',
    'DestAirportID',
    'Dest',
    'DestCityName',
    'DestState',
    'CRSDepTime',
    'DepTime',
    'DepDelay',
    'DepDelayMinutes',
    'CRSArrTime',
    'ArrTime',
    'ArrDelay',
    'ArrDelayMinutes',
    'Cancelled',
    'CancellationCode',
    'Diverted',
    'CRSElapsedTime',
    'ActualElapsedTime',
    'AirTime',
    'Flights',
    'Distance',
    'CarrierDelay',
    'WeatherDelay',
    'NASDelay',
    'SecurityDelay',
    'LateAircraftDelay'
]

In [4]:
file_path = "../../datasets/t_ontime_small.csv"

delay = spark.read.csv(file_path,header=False)
delay = delay.toDF(*cols)

In [5]:
delay

DataFrame[Year: string, Quarter: string, Month: string, DayofMonth: string, DayOfWeek: string, FlightDate: string, Reporting_Airline: string, DOT_ID_Reporting_Airline: string, IATA_CODE_Reporting_Airline: string, Tail_Number: string, Flight_Number_Reporting_Airline: string, OriginAirportID: string, Origin: string, OriginCityName: string, OriginState: string, DestAirportID: string, Dest: string, DestCityName: string, DestState: string, CRSDepTime: string, DepTime: string, DepDelay: string, DepDelayMinutes: string, CRSArrTime: string, ArrTime: string, ArrDelay: string, ArrDelayMinutes: string, Cancelled: string, CancellationCode: string, Diverted: string, CRSElapsedTime: string, ActualElapsedTime: string, AirTime: string, Flights: string, Distance: string, CarrierDelay: string, WeatherDelay: string, NASDelay: string, SecurityDelay: string, LateAircraftDelay: string]

In [6]:
delay.limit(20).toPandas()

22/10/25 13:42:53 WARN package: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,...,CRSElapsedTime,ActualElapsedTime,AirTime,Flights,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2014,1,1,30,4,2014-01-30,AA,19805,AA,N006AA,...,75,76,56,1,328,0,0,0,0,0
1,2014,1,1,31,5,2014-01-31,AA,19805,AA,N003AA,...,75,84,54,1,328,11,0,9,0,0
2,2014,1,1,1,3,2014-01-01,AA,19805,AA,N002AA,...,85,78,57,1,328,0,0,0,0,0
3,2014,1,1,2,4,2014-01-02,AA,19805,AA,N002AA,...,85,79,53,1,328,0,0,0,0,0
4,2014,1,1,3,5,2014-01-03,AA,19805,AA,N014AA,...,85,75,52,1,328,0,0,0,0,0
5,2014,1,1,4,6,2014-01-04,AA,19805,AA,N010AA,...,85,80,57,1,328,0,0,0,0,0
6,2014,1,1,5,7,2014-01-05,AA,19805,AA,N011AA,...,85,78,58,1,328,0,0,0,0,0
7,2014,1,1,6,1,2014-01-06,AA,19805,AA,N002AA,...,85,77,52,1,328,0,0,0,0,30
8,2014,1,1,7,2,2014-01-07,AA,19805,AA,N012AA,...,85,83,50,1,328,0,0,0,0,27
9,2014,1,1,8,3,2014-01-08,AA,19805,AA,N014AA,...,85,97,63,1,328,0,0,0,0,0
10,2014,1,1,9,4,2014-01-09,AA,19805,AA,N013AA,...,85,80,58,1,328,0,80,0,0,11
11,2014,1,1,10,5,2014-01-10,AA,19805,AA,N008AA,...,85,80,54,1,328,0,0,0,0,0
12,2014,1,1,11,6,2014-01-11,AA,19805,AA,N008AA,...,85,75,54,1,328,0,0,0,0,0
13,2014,1,1,12,7,2014-01-12,AA,19805,AA,N014AA,...,85,88,57,1,328,1,0,3,0,17
14,2014,1,1,13,1,2014-01-13,AA,19805,AA,N010AA,...,85,87,55,1,328,0,0,0,0,0
15,2014,1,1,14,2,2014-01-14,AA,19805,AA,N598AA,...,85,76,58,1,328,0,0,0,0,0
16,2014,1,1,15,3,2014-01-15,AA,19805,AA,N005AA,...,85,74,51,1,328,0,0,0,0,0
17,2014,1,1,16,4,2014-01-16,AA,19805,AA,N013AA,...,85,86,52,1,328,0,0,1,0,36
18,2014,1,1,17,5,2014-01-17,AA,19805,AA,N001AA,...,85,73,51,1,328,0,0,0,0,19
19,2014,1,1,18,6,2014-01-18,AA,19805,AA,N009AA,...,85,72,50,1,328,0,0,0,0,0

In [7]:
# Same Reporting Airline and IATA Code - One can be removed
delay_same_code = delay.filter(delay["Reporting_Airline"] != delay["IATA_CODE_Reporting_Airline"])
delay_same_code.show()

+----+-------+-----+----------+---------+----------+-----------------+------------------------+---------------------------+-----------+-------------------------------+---------------+------+--------------+-----------+-------------+----+------------+---------+----------+-------+--------+---------------+----------+-------+--------+---------------+---------+----------------+--------+--------------+-----------------+-------+-------+--------+------------+------------+--------+-------------+-----------------+
|Year|Quarter|Month|DayofMonth|DayOfWeek|FlightDate|Reporting_Airline|DOT_ID_Reporting_Airline|IATA_CODE_Reporting_Airline|Tail_Number|Flight_Number_Reporting_Airline|OriginAirportID|Origin|OriginCityName|OriginState|DestAirportID|Dest|DestCityName|DestState|CRSDepTime|DepTime|DepDelay|DepDelayMinutes|CRSArrTime|ArrTime|ArrDelay|ArrDelayMinutes|Cancelled|CancellationCode|Diverted|CRSElapsedTime|ActualElapsedTime|AirTime|Flights|Distance|CarrierDelay|WeatherDelay|NASDelay|SecurityDelay|LateAircraftDelay|
+----+-------+-----+----------+---------+----------+-----------------+------------------------+---------------------------+-----------+-------------------------------+---------------+------+--------------+-----------+-------------+----+------------+---------+----------+-------+--------+---------------+----------+-------+--------+---------------+---------+----------------+--------+--------------+-----------------+-------+-------+--------+------------+------------+--------+-------------+-----------------+
+----+-------+-----+----------+---------+----------+-----------------+------------------------+---------------------------+-----------+-------------------------------+---------------+------+--------------+-----------+-------------+----+------------+---------+----------+-------+--------+---------------+----------+-------+--------+---------------+---------+----------------+--------+--------------+-----------------+-------+-------+--------+------------+------------+--------+-------------+-----------------+

In [8]:
# Total 21 Airlines
delay.select('Reporting_Airline').distinct().collect()

[Row(Reporting_Airline='UA'),
 Row(Reporting_Airline='AA'),
 Row(Reporting_Airline='EV'),
 Row(Reporting_Airline='B6'),
 Row(Reporting_Airline='DL'),
 Row(Reporting_Airline='OO'),
 Row(Reporting_Airline='F9'),
 Row(Reporting_Airline='US'),
 Row(Reporting_Airline='MQ'),
 Row(Reporting_Airline='HA'),
 Row(Reporting_Airline='AS'),
 Row(Reporting_Airline='FL'),
 Row(Reporting_Airline='VX'),
 Row(Reporting_Airline='WN'),
 Row(Reporting_Airline='NK'),
 Row(Reporting_Airline='OH'),
 Row(Reporting_Airline='G4'),
 Row(Reporting_Airline='9E'),
 Row(Reporting_Airline='YV'),
 Row(Reporting_Airline='YX'),
 Row(Reporting_Airline='QX')]

In [9]:
# Analyzing Airport Related Columns
airport_cols = ["OriginAirportID", "Origin", "OriginCityName", "OriginState", "DestAirportID", "Dest", "DestCityName", "DestState"]
airport_info_selected = delay.select(*airport_cols).show()

+---------------+------+--------------------+-----------+-------------+----+--------------------+---------+
|OriginAirportID|Origin|      OriginCityName|OriginState|DestAirportID|Dest|        DestCityName|DestState|
+---------------+------+--------------------+-----------+-------------+----+--------------------+---------+
|          11298|   DFW|Dallas/Fort Worth...|         TX|        12278| ICT|         Wichita, KS|       KS|
|          11298|   DFW|Dallas/Fort Worth...|         TX|        12278| ICT|         Wichita, KS|       KS|
|          12278|   ICT|         Wichita, KS|         KS|        11298| DFW|Dallas/Fort Worth...|       TX|
|          12278|   ICT|         Wichita, KS|         KS|        11298| DFW|Dallas/Fort Worth...|       TX|
|          12278|   ICT|         Wichita, KS|         KS|        11298| DFW|Dallas/Fort Worth...|       TX|
|          12278|   ICT|         Wichita, KS|         KS|        11298| DFW|Dallas/Fort Worth...|       TX|
|          12278|   ICT|         Wichita, KS|         KS|        11298| DFW|Dallas/Fort Worth...|       TX|
|          12278|   ICT|         Wichita, KS|         KS|        11298| DFW|Dallas/Fort Worth...|       TX|
|          12278|   ICT|         Wichita, KS|         KS|        11298| DFW|Dallas/Fort Worth...|       TX|
|          12278|   ICT|         Wichita, KS|         KS|        11298| DFW|Dallas/Fort Worth...|       TX|
|          12278|   ICT|         Wichita, KS|         KS|        11298| DFW|Dallas/Fort Worth...|       TX|
|          12278|   ICT|         Wichita, KS|         KS|        11298| DFW|Dallas/Fort Worth...|       TX|
|          12278|   ICT|         Wichita, KS|         KS|        11298| DFW|Dallas/Fort Worth...|       TX|
|          12278|   ICT|         Wichita, KS|         KS|        11298| DFW|Dallas/Fort Worth...|       TX|
|          12278|   ICT|         Wichita, KS|         KS|        11298| DFW|Dallas/Fort Worth...|       TX|
|          12278|   ICT|         Wichita, KS|         KS|        11298| DFW|Dallas/Fort Worth...|       TX|
|          12278|   ICT|         Wichita, KS|         KS|        11298| DFW|Dallas/Fort Worth...|       TX|
|          12278|   ICT|         Wichita, KS|         KS|        11298| DFW|Dallas/Fort Worth...|       TX|
|          12278|   ICT|         Wichita, KS|         KS|        11298| DFW|Dallas/Fort Worth...|       TX|
|          12278|   ICT|         Wichita, KS|         KS|        11298| DFW|Dallas/Fort Worth...|       TX|
+---------------+------+--------------------+-----------+-------------+----+--------------------+---------+
only showing top 20 rows

In [10]:
# Duplicate Data because of Airports specific Column. The distinct airport can be moved to another DF.
# Apart from OriginAirportID and DestAirportID, other columns can be removed.
origin_airport_cols = ["OriginAirportID", "Origin", "OriginCityName", "OriginState"]
origin_airport_info_selected = delay.select(*origin_airport_cols)

dest_airport_cols = ["DestAirportID", "Dest", "DestCityName", "DestState"]
dest_airport_info_selected = delay.select(*dest_airport_cols)

emptyRDD = spark.sparkContext.emptyRDD()
schema = StructType([
  StructField('AirportID', StringType(), True),
  StructField('CityCode', StringType(), True),
  StructField('CityName', StringType(), True),
  StructField('StateCode', StringType(), True)
  ])
airport_df = spark.createDataFrame(emptyRDD,schema)
airport_df=airport_df.union(origin_airport_info_selected)
airport_df=airport_df.union(dest_airport_info_selected)

airport_df = airport_df.distinct()
print("Distinct Airports: "+str(airport_df.count()))
airport_df.show(truncate=False)
airport_df.repartition(1).write.csv("../../datasets/airports.csv")

Distinct Airports: 394

+---------+--------+-------------------------+---------+
|AirportID|CityCode|CityName                 |StateCode|
+---------+--------+-------------------------+---------+
|12892    |LAX     |Los Angeles, CA          |CA       |
|12889    |LAS     |Las Vegas, NV            |NV       |
|11995    |GSO     |Greensboro/High Point, NC|NC       |
|10469    |AZO     |Kalamazoo, MI            |MI       |
|14057    |PDX     |Portland, OR             |OR       |
|12511    |JLN     |Joplin, MO               |MO       |
|15624    |VPS     |Valparaiso, FL           |FL       |
|11146    |CRW     |Charleston/Dunbar, WV    |WV       |
|14457    |RAP     |Rapid City, SD           |SD       |
|13388    |MMH     |Mammoth Lakes, CA        |CA       |
|15497    |UST     |St. Augustine, FL        |FL       |
|11066    |CMH     |Columbus, OH             |OH       |
|11308    |DHN     |Dothan, AL               |AL       |
|11292    |DEN     |Denver, CO               |CO       |
|11726    |FOE     |Topeka, KS               |KS       |
|14489    |RDM     |Bend/Redmond, OR         |OR       |
|15841    |WRG     |Wrangell, AK             |AK       |
|11109    |COS     |Colorado Springs, CO     |CO       |
|10155    |ACT     |Waco, TX                 |TX       |
|10792    |BUF     |Buffalo, NY              |NY       |
+---------+--------+-------------------------+---------+
only showing top 20 rows

In [8]:
# Check Data with Code US, FL and VX - Code not found on the official IATA website
delay.select('IATA_CODE_Reporting_Airline').distinct().collect()

[Row(IATA_CODE_Reporting_Airline='UA'),
 Row(IATA_CODE_Reporting_Airline='AA'),
 Row(IATA_CODE_Reporting_Airline='EV'),
 Row(IATA_CODE_Reporting_Airline='B6'),
 Row(IATA_CODE_Reporting_Airline='DL'),
 Row(IATA_CODE_Reporting_Airline='OO'),
 Row(IATA_CODE_Reporting_Airline='F9'),
 Row(IATA_CODE_Reporting_Airline='US'),
 Row(IATA_CODE_Reporting_Airline='MQ'),
 Row(IATA_CODE_Reporting_Airline='HA'),
 Row(IATA_CODE_Reporting_Airline='AS'),
 Row(IATA_CODE_Reporting_Airline='FL'),
 Row(IATA_CODE_Reporting_Airline='VX'),
 Row(IATA_CODE_Reporting_Airline='WN'),
 Row(IATA_CODE_Reporting_Airline='NK'),
 Row(IATA_CODE_Reporting_Airline='OH'),
 Row(IATA_CODE_Reporting_Airline='G4'),
 Row(IATA_CODE_Reporting_Airline='9E'),
 Row(IATA_CODE_Reporting_Airline='YV'),
 Row(IATA_CODE_Reporting_Airline='YX'),
 Row(IATA_CODE_Reporting_Airline='QX')]

In [9]:
# Casting the FlightDate column as Date. It would help with future computations
delay = delay.withColumn("FlightDate", delay["FlightDate"]
                                  .cast('date'))

In [10]:
delay

DataFrame[Year: string, Quarter: string, Month: string, DayofMonth: string, DayOfWeek: string, FlightDate: date, Reporting_Airline: string, DOT_ID_Reporting_Airline: string, IATA_CODE_Reporting_Airline: string, Tail_Number: string, Flight_Number_Reporting_Airline: string, OriginAirportID: string, Origin: string, OriginCityName: string, OriginState: string, DestAirportID: string, Dest: string, DestCityName: string, DestState: string, CRSDepTime: string, DepTime: string, DepDelay: string, DepDelayMinutes: string, CRSArrTime: string, ArrTime: string, ArrDelay: string, ArrDelayMinutes: string, Cancelled: string, CancellationCode: string, Diverted: string, CRSElapsedTime: string, ActualElapsedTime: string, AirTime: string, Flights: string, Distance: string, CarrierDelay: string, WeatherDelay: string, NASDelay: string, SecurityDelay: string, LateAircraftDelay: string]