In [3]:
import pandas as pd
import numpy as np
import sqlite3
import sqlalchemy
from sqlalchemy import create_engine

In [4]:
file_path = "../../datasets/air_carriers.csv"

In [15]:
df = pd.read_csv(file_path, names=['IATACode', 'ICAOCode', 'AirCarrierName'], header=0)

In [19]:
air_carriers = df.set_index('IATACode')

In [20]:
air_carriers

         ICAOCode                AirCarrierName
IATACode
ZW            AWI                 Air Wisconsin
AS            ASA               Alaska Airlines
G4           AAY             Allegiant Air LLC
AA            AAL             American Airlines
C5           UCA                 Champlain Air
CP           CPZ              Compass Airlines
DL           DAL         Delta Air Lines, Inc.
EM           CFS                Empire Airline
9E           EDV                  Endeavor Air
MQ           ENY                     Envoy Air
EV           ASQ           ExpressJet Airlines
F9           FFT       Frontier Airlines, Inc.
G7           GJS                GoJet Airlines
HA           HAL        Hawaiian Airlines Inc.
QX           QXE                   Horizon Air
B6           JBU   Jetblue Airways Corporation
OH           JIA                Jetstream Intl
YV           ASH           Mesa Airlines, Inc.
KS           NLA                        Penair
PT           PDT             Piedmont Airlines
YX           RPA             Republic Airlines
OO           SKW              Skywest Airlines
WN           SWA            Southwest Airlines
NK           NKS         Spirit Airlines, Inc.
AX           LOF                   Trans State
UA           UAL         United Airlines, Inc.

In [17]:
db_path = "../../dbs/delays.db"

In [18]:
conn = sqlite3.connect(db_path)
conn.execute("DROP TABLE IF EXISTS air_carriers;")

create_query = ''' \
            CREATE TABLE air_carriers
            ( 
                IATACode                       VARCHAR, 
                ICAOCode                       VARCHAR,
                AirCarrierName                 VARCHAR
            );
    '''
conn.execute(create_query)
conn.close()
engine = sqlalchemy.create_engine("sqlite:///"+db_path, echo=False)

In [21]:
engine = sqlalchemy.create_engine("sqlite:///"+db_path, echo=False)
air_carriers.to_sql('air_carriers', con=engine, if_exists='append', index=False)

26